Add error-field to force invalid form
LifeSG/validation-schema-generator pull request #58
Opened 2024-09-19 01:06 UTC by qroll

**Changes**

- A field that when present, forces the form to be invalid
- Exposes an `error` rule to customise the message
-   [delete] branch

**Changelog entry**

-   Add support for `error-field`

2024-09-25 01:14 UTC, weili-govtech commented
can we update it according to the changes in FEE?
- tighten validation type
- add children

2024-09-25 09:40 UTC, qroll commented
the change to let custom rules extend `IUnitNumberFieldValidationRule` actually ended up causing more issues
- on Typescript 4, I get [this error](https://github.com/microsoft/TypeScript/issues/44373)
- in `yup-helper.ts`, the rules couldn't be recognised due to the intersection of e.g. `IUnitNumberFieldValidationRule | IYupValidationRule` stripping away non-common rules

in the end I excluded the error field from `TFieldValidation` because it doesn't contribute to the typical rule evaluation anyway

2024-09-26 01:28 UTC, weili-govtech requested changes

2024-09-26 01:28 UTC, weili-govtech commented on src/schema-generator/types.ts
> +export type TFieldValidation = Exclude<TFieldSchema, IErrorFieldSchema>["validation"];
I think this is not needed, instead the rest of the custom rules in schemas should extend from `IYupValidation` (looks like we really missed this out)

2024-09-30 15:46 UTC, weili-govtech approved these changes

2024-09-30 15:46 UTC, merged